project:
  type: website
  preview: 
    port: 4200
  output-dir: docs
  # this says render all qmd, md, rmd files but nothing in labs or working
  render: 
    - "*.qmd"
    - "*.md"
    - "*.Rmd"
    - "!labs/"
    - "!lab-templates/"
    - "!working/"
    - "!inclass/"
    - "!projects.qmd"

website:
  favicon: assets/img/favicon.ico
  title: "Data reporting for investigative journalism"
  page-navigation: true
  
  navbar:
    logo: assets/img/djlogo.png
    background: secondary
    max-width: 2400px
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cronkitedata/maij-data/
    left: 
      - icon: house-door-fill
        # otherwise it fills with "Data reporting" or site name
        text: " "
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Weeks"
        file: weeks.qmd

# can't figure out how to get the fontawesome icon in the home button. Oh well. 

  sidebar: 
    style: docked
    search: true
    background: light
    collapse-level: 1
    contents: 
      - file: index.qmd
        text: "Home"
      # updates gets auto filled by changes in posts/
      - section: "Updates"
        file: updates.qmd
      - text: "---"
      - file: syllabus.qmd
        text: "Syllabus"
      - file: schedule.qmd
        text: "Course schedule"
      - text: "---"
      # I have to list them, otherwise they show up with the title
      - section: Weekly details 
        file: weeks.qmd
        #this has to be changed with each schedule. Be careful about it. 
        contents: 
          - text: "1.1: Intros"
            file: weeks/week01-1.qmd
          - text: "1.2: Startup potpourri"
            file: weeks/week01-2.qmd
          - text: " 2: Scripted journalism"
            file: weeks/week02.qmd
          - text: "3.1: First steps in data analysis"
            file: weeks/week03-1.qmd
          - text: "3.2: A quick tour of verbs"
            file: weeks/week03-2.qmd
          - text: "4.1: Filter and sort to find stories"
            file: weeks/week04-1.qmd
          - text: "4.2: Creating new from old with mutate"
            file: weeks/week04-2.qmd
          - text: "5.1: Summarize with group by"
            file: weeks/week05-1.qmd
          - text: "5.2: Matchmaking with joins"
            file: weeks/week05-2.qmd
          # - text: "6: The power of regular expressions"
          #   file: weeks/week06.qmd
          # - text: "7: TK"
          #   file: weeks/week07.qmd
          - text: "8: Cognitive bias in data journalism"
            file: weeks/week08.qmd
          # - text: "8-2: The life of data"
          #   file: weeks/week08-2.qmd
          # - text: "9-1: Visualization as a reporting tool"
          #   file: weeks/week09.qmd
          # - text: "9-2: Intro to GIS and mapping"
          #   file: weeks/week11.qmd
      - text: "----"
      - text: Course textbook
        href: https://cronkitedata.github.io/djtextbook
        # change canvas and slack each year
      - text: Canvas 
        href: https://asu.instructure.com/courses/171974
      - text: Slack
        href: https://app.slack.com/client/T068BE4K9QU/C068BF87G9J
      - text: Other links
        href: https://start.me/p/nRyOGj/public-page
      - text: "---"

format:
  html:
    theme: [sandstone, theme.scss]
    max-width: 1920px
    page-layout: full
    toc: true
#    toc-location: left
#    toc-depth: 2
    toc-expand: 3
    header-includes: |
       <meta name="robots" content="noindex">
    published-title: "Class date"

engine: knitr






