project:
  type: website
  preview: 
    port: 4200
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.md"
    - "*.Rmd"
    - "!labs/"
    - "!prelabs/"
    - "!working/"

website:
  favicon: assets/img/favicon.ico
  title: "Data reporting for investigative journalism"
  page-navigation: true
  
  navbar:
    logo: assets/img/djlogo.png
    background: primary
    max-width: 2400px
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cronkitedata/maijdata/
      - icon: twitter
        href: https://twitter.com/sarah_h_cohen/
    left: 
      - icon: house-door-fill
        # otherwise it fills with "Data reporting" or site name
        text: " "
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Weeks"
        file: weeks.qmd

# can't figure out how to get the fontawesome icon in the home button. Oh well. 

  sidebar: 
    style: docked
    search: true
    background: light
    collapse-level: 1
    contents: 
      - file: index.qmd
        text: "Home"
      - section: "Updates"
        file: updates.qmd
        contents: 
          - auto: posts/*
      - text: "---"
      - file: syllabus.qmd
        text: "Syllabus"
      - file: schedule.qmd
        text: "Course schedule"
      - text: "---"
      # I have to list them, otherwise they show up with the title
      - section: Weekly details 
        file: weeks.qmd
        contents: 
          - text: "1.1: Intros"
            file: weeks/week01-1.qmd
          - text: "1.2: Reading the story"
            file: weeks/week01-2.qmd
          - text: " 2: Replication / spreadsheet review"
            file: weeks/week02.qmd
          - text: "3.1: The life of data"
            file: weeks/week03-1.qmd
          - text: "3.2: Install party!"
            file: weeks/week03-2.qmd
          - text: "4.1: Your first R program"
            file: weeks/week04-1.qmd
          - text: "4.2: An example analysis: Billboard Hot 100"
            file: weeks/week04-2.qmd
          - text: "5: In-depth verbs pt 1"
            file: weeks/week05.qmd
          - text: "6: In-depth verbs pt 2"
            file: weeks/week06.qmd
          - text: "7: In-depth verbs pt 3"
            file: weeks/week07.qmd
      - text: "----"
      - text: Course textbook
        href: https://cronkitedata.github.io/djtextbook
      - text: Canvas 
        href: https://asu.instructure.com/courses/138967
      - text: Slack
        href: https://asu-2231-mco510-21913.slack.com/
      - text: Other links
        href: https://start.me/p/nRyOGj/public-page
      - text: "---"

format:
  html:
    theme: [sandstone, theme.scss]
    max-width: 1920px
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 3
    header-includes: |
       <meta name="robots" content="noindex">
    published-title: "Class date"

engine: knitr

# Beginning in version 1.3, we can use the grid options to make the left margin smaller. I'm not sure what it
# does to responsiveness, but I believe that it works fine. 
# consider using that in the future. (Current version is 1.2)





