---
title: "Preliminary schedule at a glance"
description: "A broad outline of what we'll be doing"
---

## Schedule and assignment logistics {.unlisted}

This is a preliminary schedule that will probably change as we move along. You may want to spend more or less time on a topic, or we might have some guest speakers. I'll try to keep this updated as we go along.

The due dates listed here are only for scheduled assigments. Expect to have a lab and / or a walkthrough due nearly every day.

+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| Week     | Dates      | Topics                                                                      | Deadlines                                                                                      |
+==========+============+=============================================================================+================================================================================================+
| 01       | Jan 8-10   | The journalistic method; Intro to programming                               | Su 1/7: Pre-class survey; Slack setup <br> Fri 1/12: Cronkite integrity pledge, R installation |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 02       | Jan 17     | Scripted journalism with Quarto                                             | W 1/17: What would you do? (25)                                                                |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 03       | Jan 22 -24 | From documentation to data: First steps\                                    |                                                                                                |
|          |            | A tour of tidyverse vebs                                                    |                                                                                                |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 04       | Jan 29 -31 | Verbs Pt 1: Filter, arrange, mutate                                         |                                                                                                |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 05       | Feb 5-7    | Verbs Pt 2: Group by, summarize                                            | Su 2/4: Replication project sentences (50)                                                     |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 06       | Feb 12-14  | Joining to add columns from other datasets                                  | Su 2/11: Life of a dataset (50)                                                                |
|          |            | Intro to regular expressions                                                |                                                                                                |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 07       | Feb 19-21  | Tablemaking and presenting your results;\                                   | Su 2/18: Replication project update (50)                                                       |
|          |            | Lab for replication project                                                 |                                                                                                |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 08       | Feb 26     | Numbers in the newsroom; Ethics and cognitive bias in data journalism       |  Su 2/25: Replication project final (75) <br> Fri 3/1: Find 3 datasets (50)                    |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
|          |            | SPRING BREAK                                                                |                                                                                                |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 09       | Mar 11-13  | Data viz part 1 : Viz as a reporting tool ; lab for viz and start-to-finish | We 3/13: Memo proposal (25)                                                                    |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 10       | Mar 18-20  | Data viz part 2: Mapping to find stories                                    | Su 3/17: Start to finish exercise (50)\                                                        |
|          |            |                                                                             | We 3/20: What would you do?                                                                    |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 11       | Mar 25-27  | Scraping                                                                    | Su 3/24: First memo update (50) <br> We 3/27: What would you do? (25)                          |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 12       | Apr 1-3    | Cleaning data with openRefine; convert PDF reports to data;                 | Su 3/31: Second memo update (50)\                                                              |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 13       | Apr 8-10   | Story memo lab ; Build your own database                                    | Su 4/7: Build your own database (50) We 4/10: What would you do? (25)                          |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 14       | Apr 15-17  | Advanced spreadsheets;                                                      | Su 4/14: Final story memo (100) <br>                                                           |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| 15       | Apr 22-24  | Creating a Github site for job-hunting; paying it forward                   |                                                                                                |
+----------+------------+-----------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+

: {.striped tbl-colwidths="\[5, 15, 50, 35\]"}