---
title: Ethics in data journalism
date:  2023-03-19
draft: false
description:  After going through the replication project, we'll look at some specific issues related to statistics and other problems in data reporting.
---


## Agenda
.

### Monday 3/20

* We spent some time regrouping and planning, and also a demo of some table-making packages. [That chapter is in the textbook](https://cronkitedata.github.io/djtextbook/vis-tables.html).


### Wednesday 3/22

* Review the replication project 
* Statistical overview for data journalism
* Discuss "What would you do?" on scraping (which conveniently is the main thing in ethics!)


## Upcoming deadlines

[Wednesday 3/22]{.sked-dates}: What would you do? Scraping edition

[Sunday 3/26]{.sked-dates} : Memo proposal

[Monday 4/3]{.sked-dates} : What would you do? (Census race and ethnicity)  

[Sunday 4/9]{.sked-dates}: First memo update


## Preparation

### For Wednesday

- “[How to prevent confirmation bias affecting your journalism](https://onlinejournalismblog.com/2020/04/07/how-to-prevent-confirmation-bias-affecting-your-journalism/)” Paul Bradshaw, Online Journalism Blog. This is a particularly big problem in data journalism, since we often seek out stories in databases based on tips or broad ideas, and can often find them. 

- **Optional**, also by Bradshaw: “[A journalist’s guide to cognitive bias (and how to avoid it)](https://onlinejournalismblog.com/2020/03/24/a-journalists-guide-to-cognitive-bias-and-how-to-avoid-it/)” for other kinds of biases that we might bring to our reporting. These include common problems in newsrooms, such as a “sunk-cost” bias or a negativity bias.

- Just the video [BBC Worklife, How ‘survivorship bias’ can cause you to make mistakes](https://www.bbc.com/worklife/article/20200827-how-survivorship-bias-can-cause-you-to-make-mistakes)  

- “[Fighter pilots and firing coaches](https://faculty.mccombs.utexas.edu/carlos.carvalho/teaching/regression_to_the_mean.pdf)”, Brian Burke, 2009, in Advanced Football Analytics, with an explanation of regression to the mean. (This link is to a printout of the original piece, since the website version is a little bit of a mess.) It isn’t very well written, but it eventually gets around to an anecdote about fighter pilots and the concept we care about: “regression to the mean”.


- The videos # 1-4 from the Knight Center for the Americas on “Equity and Ethics in Data Journalism’s” module 3 (links below). I’m not thrilled with the pace or specific content with these videos, but they’re the best single spot I’ve found for these common problems. **Feel free to speed this up considerably.** I found that 1.75 was the right speed for me! (She talks about writing data journalism stories, but she’s never been a journalist of any kind. Sigh.)

   * [Common mistakes in data analysis](https://youtu.be/4ndrF2cSqVo)
   * [Causal mistakes in data](https://youtu.be/9nKs7mJukSk)
   * [Simpson’s paradox in data journalism](https://youtu.be/f5gMwGfZL3g)
   * [Prosecutor’s Fallacy in data journalism](https://youtu.be/0y3sco0lKzc) OR [this piece on prosecutor’s fallacy](https://towardsdatascience.com/the-prosecutors-fallacy-cb0da4e9c039) by Ray Johns, 2019.



## Textbook chapters

There's nothing for preparation, but there is a [chapter on better looking tables](https://cronkitedata.github.io/djtextbook/vis-tables.html). I'm not very good at the snippets I showed in class, so I don't have a tutorial on that.