---
title: Building your own database
date:  2024-03-10
draft: false
description:  Now that you understand the concept of tidy data, of filtering vs. counting, and of "dirty" data, you'll have an easier time imagining how to create your own database from documents and disparate sources.  
---

## Upcoming deadlines

-   [Friday 3/15]{.sked-dates}: Data memo proposal. (25)  NOTE THE FRIDAY DEADLINE
-   [Sunday 3/17]{.sked-dates}: Build your own database assignment (50)
-   [Wednesday 3/20]{.sked-dates}:  What would you do? (25)

## Monday 3/11

### Agenda

-   Regroup and review revised syllabus and schedule
-   Introduction to the story memo project. 
-   Regular expressions -- using pattern matching. We'll do a walkthrough in class.  This will be helpful when you have to figure out how to enter things into a database, since you can use pattern matching to find what you entered.

### Preparation

- Review the Canvas module on the Story Memo project, which is listed at the top of the modules. Be sure to review the page that introduces you to the details and the assignment due on Friday. 

## Wednesday 3/13

-  Building your own database.  Guest speaker: Daniela Porat, Law360, co-author of the multiple shootings story. 
 
### Preparation for Wednesday

* [Build your own database](https://cronkitedata.github.io/djtextbook/start-build-own.html) chapter from the textbook. Pay particular attention to the things that were and were not done in each of the examples. 

* Review the structure of the [Gun Violence Archive's mass shooting database](https://www.gunviolencearchive.org/reports/mass-shooting), being sure to click on a few of the "View Incident" links. (There are two links on each line. One has the original "source" they used, such as a news report. The other has details of the "incident" that they typed into their database.) Think about how this would work in a database. 

* You've already read the story,  "[A drumbeat of multiple shootings, but no one is listening](https://www.nytimes.com/2016/05/23/us/americas-overlooked-gun-violence.html)", by Sharon LaFraniere, Daniela Porat and Agustin Armendariz. I want you to **read it again carefully** and think about what a database would look like if you wanted to use it to look up information for the story. Think about what you want to count ( categories) vs. what you want to search/filter (more free or less common).   

* Make sure you can sign in to Airtable using the [SSO link](https://airtable.com/sso/login?) and your ASU credentials.



