---
title: Getting started with programming - a walkthrough
date:  2022-01-30
description: You can now ditch those painstaking data diaries and write self-documenting programs using R and Quarto. 
--- 

## Agenda 

* Discussion of "life of a dataset" assignment
* Questions about the R Studio tour and tutorials
* Create your first document

## Upcoming deadlines

* [Today]{.sked-dates} : Your first [Quarto doc](https://raw.githubusercontent.com/cronkitedata/maij-data/main/prelabs/prelab01-yourname.qmd)
* [Monday Feb. 6]{.sked-dates} : "What would you do?" : choosing a data source. See assignment in Canvas.


## Preparation

This prep might leave you feeling bewildered. Don't let it get to you. You will get used to the look and feel of the software and some of the technical language soon. You don't have to internalize all of this. Instead, try to get used to the screen and the process of typing the commands into the computer. You'll probably get a lot of errors, and that's fine --- they're not judging you. They're supposed to be hints, even when they're [red]{.text-danger} and use words that look like *$#u893q#r32*.

* Review the textbook chapter, "[Getting started with R and RStudio](https://cronkitedata.github.io/djtextbook/r-start.html)"

    * Make sure to install the packages at the beginning of the chapter. (We might have been able to get this part done in class already -- we'll see how it goes.) You might want to get it going and then get a cup of tea -- it will take at least a few minutes once it starts and could take longer. It might look like it's stalled. If you have trouble at this point, please post a question to `#dj-sos` Slack channel and describe what's happening. 

    * Try the ["Programming basics" tutorial](https://posit.cloud/learn/primers/1.2) linked in that chapter. Don't worry about all of the math in it; you don't have to go through the part where you answer questions. Instead, just focus on the concepts of the 1-minute videos:  functions, arguments, objects and data types.^[I tried to make a version of the videos for you and failed miserably.]  

    * Watch Andrew Heiss's [RStudio tour](https://youtu.be/cnQ-v1UUWyE). Again, don't worry much about how math-centric it is. Our work will be much less so. But he does a good job of going through the most confusing pieces of what's in front of you. 

**Don't spend more than 2 hours on this. You might finish sooner, but you'll need this to move forward so don't rush. I also expect you'll have questions when we get to class.**


OPTIONAL: If you are nervous, consider reviewing the [Using Quarto](https://cronkitedata.github.io/djtextbook/r-quarto.html) chapter that we'll be following in our class lab today. 

## Textbook chapters we'll review

* [A gentle introduction to programming](https://cronkitedata.github.io/djtextbook/appendix-program.html)
* [Creating Quarto documents](https://cronkitedata.github.io/djtextbook/r-quarto.html)




