---
title: "Verbs in depth part 2: Group, mutate, join"
date:  "2022-02-14"
draft: true
description: This is our last week with verbs -- once this week is done, you'll have the tools to do most of what reporters do with data! 
--- 


This is our last week of basic verbs. With `select`, `arrange`, `filter`, `summarise`, `group_by` and now `join` , you'll have most of what you need to analyze data in R! Next week we'll start working to put it all into practice in a warm-up story memo project, and you'll start seeing how to make your markdowns and data readable. 


## Agenda

### Monday

Walkthrough on `mutate` and `group_by`/`summarise`.  You'll do the teaching!

### Wednesday

The last verb: `join`. Looking at industries, and thinking of stories. 



## Upcoming deadlines

Sunday 2/20
{.text-dark}
Your proposal for the [replication project](/dataj/replication/).


Friday 3/4 
{.text-dark}
Update on the replication project. 


## Preparation and learning materials 

We'll be walking through chapters in the textbook this week, and you don't have anything else.  Instead, spend some time looking at the story choices for the replication project so you make a smart choice and study the sentences to come up with the ones you want to replicate.








