---
title: "Introductions"
date: 2024-01-8
description: "Agenda and preparation for the first day"
draft: false
--- 


  <blockquote class="blockquote-big mb-3">
    <p>Maybe stories are just data with a soul</p>
    <span> --- Brené Brown </span>
  </blockquote>
  

I’ll use this structure to lay out weely agendas, upcoming deadlines, readings, tutorials and more.  When you have to turn something in, the full instructions are in a Canvas assignment. 
 

Each of these weekly pages contains a section called "[Preparation](#preparation)."  You should read, watch or listen closely and try to follow along on all of the tutorials **before** that class. Skimming or a cursory glance won't be good enough.

Today's preparation is due before class begins on Jan. 8.


::: {.callout-note}
These readings are not shown as "assignments" in Canvas, so they are not on your front page every day. Each day's page on this site is linked from the Canvas module. You don't have to remember to visit the course website or textbook separately.
::: 

## Agenda

We'll skip the usual slide presentation introducing you to data reporting -- Caitlin went over it in boot camp, and the readings are probably a more interesting introduction. 

* Introductions - you and me
* Logistics
* Syllabus exercise
* The journalistic method reading review
 

## Upcoming deadlines

[Sunday Jan. 7]{.sked-dates}

* [Survey of skills](https://docs.google.com/forms/d/e/1FAIpQLSdah962tKxkjV-xI5-3T3ZvtjHJbUA5NQqCzZNn-dDHS4Xk1w/viewform?usp=share_link) and interests via Google drive. You must sign into Google Docs using your ASU email to get access --- I can't give access outside of the university for this one. (This should only take about 10 minutes)

[Monday, Jan. 8]{.sked-dates} before class begins:

 * Complete the Slack assignment under Class Zero in Canvas. 
 * Do the [preparation](#preparation) below. This will be true every day of the semester, so I won't list it separately in the future.  

[Friday, Jan. 12]{.sked-dates} : 

* Setting up your computer
* Cronkite Academic Integrity pledge in Canvas 

[Wednesday, Jan. 17]{.sked-dates} :  What would you do? Reporting live election results


## Preparation
[Estimated time: less than an hour]{.small-note}

Every day, you'll see this section in the weekly details page. All of the reading and preparation are expected to have been done before you get to class. We'll all waste our time if you don't prepare for class. 

* [Syllabus](../syllabus.qmd). Bring questions, comments or complaints to class on Monday. 

* [Preface to the class textbook](https://cronkitedata.github.io/djtextbook)

* Welcome from Ron Nixon, vice president for investigations, the Associated Press

{{< video https://www.youtube.com/embed/olF0RQS02HA  width="400">}}


American journalists have been using empirical methods since the birth of the republic. Read the materials with an eye for the methods they describe --- data collection, counting and analyzing --- and the sources they used. You're not expected to follow links or watch related material unless I mention them. 

*Come to class prepared to discuss a passage from one of these pieces that caught your eye.*

* [The Journalistic Method: Five principles for blending analysis and narrative](https://journalistsresource.org/tip-sheets/journalistic-method-tip-sheet-blending-analysis-narrative/), by Nicholas Lemann, former dean of the Columbia University Graduate School of Journalism.

* [Ida B. Wells used data journalism to fight lynching](https://www.vox.com/2015/7/16/8979771/ida-b-wells-lynching-data), Dara Lind, Vox.com, July 2015

* [The Myth of the Machine](https://cronkitedata.s3.us-west-1.amazonaws.com/docs/berens_nerds_words.pdf) Michael J. Berens, a chapter in "When Nerds and Words Collide" Poynter Institute, 1999. Although it was written nearly 25 years ago, the insights are still relevant today.

* [Introduction to Precision Journalism](https://cronkitedata.s3.us-west-1.amazonaws.com/docs/precision-journalism.pdf), Sage Encyclopedia of Journalism. 

 

