---
title: "Replication and your first R program"
date:   2024-01-17
description:  Using Quarto to combine your programming and your documenation in one place.
--- 

## Agenda

* Review of What Would You Do?
* Questions about the R and RStudio tour and tutorials
* Replication and documenting your work in Quarto (lab)

## Upcoming deadlines

[Today]{.sked-dates} : 
  
  * What would you do? (Live election results) (9:30 am)
  * [In-class lab](https://raw.githubusercontent.com/cronkitedata/maij-data/main/prelabs/prelab01-yourname.qmd)

## Preparation and learning materials

### Reading 
[Estimated time: less than an hour]{.small-text}

::: {.callout-caution}
## TK
  Replication and data documentation from the textbook
::: 



### Get to know R and RStudio
[Estimated time: 1-2 hours ]{.small-text}

This prep might leave you feeling bewildered. Don't let it get to you. You will get used to the look and feel of the software and some of the technical language soon. You don't have to internalize all of this. Instead, try to get used to the screen and the process of typing the commands into the computer. You'll probably get a lot of errors, and that's fine --- they're not judging you. They're supposed to be hints, even when they're [red]{.text-danger} and use words that look like *$#u893q#r32*.

::: {.callout-tip}
I usually list the readings in a suggested order. They often build on one another.
:::

* Follow along in the textbook chapter, "[Getting started with R and RStudio](https://cronkitedata.github.io/djtextbook/r-start.html)".^[This means, "Open RStudio yourself and compare your screens and your commands to the ones in the book." Don't just skim this.]

Be sure to: 

  * Install the packages at the end of the chapter. Depending on how you installed R and RStudio, this could be slow and appear that it's stopped working. Just go get some coffee and come back in a little while. 

  * Watch the [Andrew Heiss](https://youtu.be/cnQ-v1UUWyE?si=zBRWU1R53yml1jJ0) video shown in the textbook. Ignore how math-centric it is, and just concentrate on his explanation of the screens.

* **Optional** Try the [`swirl` tutorial](https://cronkitedata.github.io/djtextbook/r-start.html#optional-hands-on-tutorial) mentioned in the textbook.

* **Optional** Try the ["Programming basics" tutorial](https://posit.cloud/learn/primers/1.2) linked in that chapter. Don't worry about all of the math in it; you don't have to go through the part where you answer questions. Instead, just focus on the concepts of the 1-minute videos:  functions, arguments, objects and data types. We'll be going over these ideas in a future class, so don't feel like you need to do this unless you're feeling nervous.^[I tried to make a version of the videos for you and failed miserably.]  


## Follow-up materials

* [Creating Quarto documents](https://cronkitedata.github.io/djtextbook/r-quarto.html)

* [22-minute video](https://youtu.be/FlX75wfL9ew) that goes through what we will go through in class