---
title: "Verbs Part I: Filter and mutate"
date:  "2023-02-05"
--- 

Beginning this week, the structure for most weeks will be: 

-  Monday: Discuss reading and project progress; introduce the R skills topic and pre-lab. 
-  Wednesday: Answer questions that arose in the pre-lab and spend the rest of the time on the lab.

## Agenda

Monday: 

* *What would you do*? discussion
* Review the Hot 100 lab from last week. 
* Introduce the Paycheck Protection Program data that we'll use for the next several weeks. 
* Introduce pre-lab concepts

Wednesday: 

* Address questions or problems that came up in the pre-lab
* Lab on filter, mutate.

### Upcoming deadlines

- [Wednesday]{.sked-dates}: Pre-lab (9:30am) and lab on this week's verbs
- [Sunday Feb. 12]{.sked-dates} : The sentences you propose replicating for the data replication project
- [Sunday Feb. 19]{.sked-dates} : PPP story lines


## Preparation

### Background on PPP data

* Read the documentation/background on the Paycheck Protection Program data in the [textbook appendix](https://cronkitedata.github.io/djtextbook/appendix-ppp.html)

### PPP data stories

Review these three very different approaches to reporting on the PPP loans. While you don't need to study them, they're useful to us for several purposes. First, they show how different people attacked the data to find very different stories. In addition, they will provide you some background on the program itself, written for a lay audience. (We like that.) Finally, they're relatively old and I have yet to see good stories now that there is more information - I hope it will spark some ideas. 

* ["Hundreds of PPP Loans Went to Fake Farms in Absurd Places"](https://www.propublica.org/article/ppp-farms), Derek Willis and Lydia DePillis, ProPublica, May 18, 2021
* "[Six Stories From a Downtown District Show Pandemic's Uneven Toll](https://www.wsj.com/articles/some-asheville-businesses-thrived-with-government-backed-ppp-loans-others-struggled-11609426801)",  Anthony DeBarros and Amara Omeokwe, Wall Street Journal, Dec. 31, 2020. (Read this on campus if you haven't signed up for the free WSJ subscription through the library.)
* ["Banking on Inequity"](https://revealnews.org/podcast/banking-on-inequity/) , RevealNews, from reporting by Laura C. Morel, Mohamed Al Elew and Emily Harris, May 1, 2021. 

::: callout-note
The *Reveal*  story will be used again later in the semester, so you may want to pay particular attention to it. We might use it for a "What would you do?" , and we might make it available for your replication project. I'm still working on that.
::: 

## Chapters for the Wednesday's labs: 

* [`select`, `arrange` and `filter`](https://cronkitedata.github.io/djtextbook/r-verb-filter.html) (with a focus on filter)
* [`mutate`](https://cronkitedata.github.io/djtextbook/r-verb-mutate.html) to get new data from old




