---
title: "Matchmaking with joins"
date:  2024-02-12
description: After this last verb of the tidyverse, you'll know much of what's used in any reporting analysis. 
draft: false 
--- 


## Monday Feb 12

### Agenda

* Review joining walkthrough
* Lab for joining

### Upcoming deadlines


* [Sunday Feb. 18]{.sked-dates}:  Replication project draft
* [Sunday Feb. 25]{.sked-dates}: Final replication project
* [Friday, March 1]{.sked-dates}: Three dataset ideas. If you'll be gone, it's up to you to work this in with the rest of your schedule, and turn it in early


### Preparation

* [Verbs in Depth: Matchmaking with joins](https://cronkitedata.github.io/djtextbook/r-verb-join.html)

Now that you've done some walkthroughs on your own, they won't be provided to you for future lessons. Instead, follow along on your own with the assigned chapters, and ask for help from #dj-sos and write down your takeaways to share in class. 

## Wednesday Feb 14


### Agenda

* Open lab session for 1/2 hour to review the details of each dataset for your replication draft. 
* Walkthrough of using more advanced filters and mutate statements. These are ways to make your programs more efficient.


### Preparation

* Be sure to have started your replication project. This means fully reviewing the data documentation, loading an looking at the data in R, and trying to answer the easiest question on the list (which may not be the first one). I can't help you if you haven't tried yet. 
