---
title: "Untitled"
format: 
   html: 
     embed-resources: true
editor: visual
---

## Fix your document

Edit the YAML (front matter) above to reflect the typical settings that you'll want in your documents. It's ok to want to copy and paste it from one you've worked on before. I just want you to get in the habit of paying attention to all parts of the document.

**Add your standard libraries to a code chunk here, and run it**

Nothing else will work until you've done this.

```{r}
#| label: setup
 


```

## Load and examine the PPP data

The PPP data is stored in an R data file located here: <https://cronkitedata.s3.amazonaws.com/rdata/ppp_az_loans.RDS> . Write a code chunk that will load it into a new object called `ppp_orig` :

If you get errors, check:

-   Have you used the nested functions as shown in the chapter?
-   Is the site URL in quotes?
-   Have you loaded your libraries?

Now examine it using the methods you learned in [Chapter 15, Getting and Saving data](http://cronkitedata.github.io/djtextbook/r-data-import.html)

Add as many code chunks as you want to do accomplish this.

## Practice filtering

#### Practice questions

Write a code chunk under each of the questions below that attempts to get the list described. In each of these, you may have an easier time if you use the `select` and `arrange` verbs to look at the answers in a more compact or logical way.

After each item, describe why this might be an interesting list for a story --- why might you want to visit the place or interview the people who are listed from these queries? What story might emerge?

1.  List all of the loans worth at least \$1 million.

2.  Look at all of the projects in Maricopa County of less than \$1,000

3.  List all of the loans that were not forgiven. These are listed with `NA` in the `forgiven` amount, not 0.

4.  List all the loans to non-profit organizations in Scottsdale, Phoenix and Tempe.

5.  Find the McDonald's franchises.

HINT: You'll have to get a handle on what is actually in the data and examine your answers to make sure you got what you wanted.

### Errors

Common reasons for errors that prevent your code from running:

-   Using "=" instead of "==" in filters
-   Unbalanced quotation marks
-   Unbalanced parentheses
-   You haven't run the chunk that contains your libraries.
-   Forgetting to add a pipe (\|\>) to continue to the next line.
-   Selecting a few columns before you filter, without including the one you want to test.

Sometimes when you see an error, you might have to try running twice after you fix it -- R gets confused and thinks you're still working on the first try.

As you get these errors, try to read them and get used to what they're trying to tell you. They're really hard to read, but there's often a few words buried in them that lead you to the answer. You will also see where the error occurred, though it sometimes happens on the row *below* the one that actually has the mistake.

### Your questions

Describe **three** lists of loans you would like to examine that might lead you to businesses, people or places to interview for a story based solely on what is contained in this data. An example of this kind of list is the Wall Street Journal story you read: downtown businesses along a specific stretch of Asheville. This is JUST for looking at interesting lists, NOT for summarizing or counting or summing amounts.

For each idea, take a stab at trying to produce those lists in a code chunk or a series of code chunks.

## Mutate

Add code chunks to do the following:

1.  Using the if_else() function, create a column that shows whether or not the loan was forgiven. (None had been charged off as of the date of the data)

2.  Using the case_when() , categorize the loans as "Small", "Medium" or "Large". You choose the amounts to assign to each of those categories. We'll learn a more statisticially serious way of doing that in the future.

3.  Try to turn the date column in something by month. Here is a phrase that takes a date value, and then sets it to the first of the month that it's in:

    `floor_date ( column_name , 'month')`

4.  The [list of the first digits of the industry code](https://www.census.gov/naics/?58967?yearbck=2017) can help you determine what kind of business it was. Use a mutate statement using str_like() and case_when() to distinguish between a) retail trade , hotels or restaurants , b) Mining and agriculture, and c) Professional, technical and scientific services. Code everything as as "Other". This might be hard, and it will require some str_like / OR conditions, or you have to create a new column with just the first two digits and then test it using the `%in%` operator. Get as far as you can with this. HINT: The function `str_sub( col name, first position, last position)` lets you extract the nth characters of a string.

Use the 2017 version from the NAICS site -- 2022 wasn't invented when the loans were given. It's shown toward the bottom of the link page (I can't seem to link to it directly).

## What do you want to remember?

List three things that you want to remember from this lab. (They may not be any different than the prelab. That's ok.)

## Render if you can

This isn't a final document -- it contains instructions, your writing, a lot of code and its output, so you don't really need something as readable as usual. But rendering can give you a view of the document that you don't see in the Source or Visual modes, and can catch errors that sneak in to your code as you work. See if you can render it and look at the view. Think about how you might want to clean it up for an editor or a fellow reporter.
